<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVdFxp0u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVdFxp0u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVdFxp0u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVdFxp0u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVdFxp0u\App_KernelDevDebugContainer([
    'container.build_hash' => 'VdFxp0u',
    'container.build_id' => 'ef5ef94c',
    'container.build_time' => 1674470982,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVdFxp0u');
